### ISSUE TITLE
浏览器直接引用是有问题的？

### ISSUE THREAD

**Issue by CGerAJ** [git-lt/lite-validator#1]
http://runjs.cn/code/1rsarsvn

**Comment by CGerAJ** [comment]
重新用其他工具打包了 引用可用

**Comment by CGerAJ** [comment]
https://github.com/CGerAJ/outils/blob/master/min/outils_validForm.min.js


```
<script src="outils_validForm.min.js"></script>
  <script>
      var OS = outils.validForm()
  </script>
```
只对单个函数打包 因为我就用这一个就行 其他的自行打包

**Comment by git-lt** [comment]
不好意思这个项目已经不维护了，请不要用于生产，因为可能存在移动端的兼容性问题，所以不好意思，请使用其它开源插件代替或者自行clone之后优化一下
